name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Use the version of Node.js that you prefer

    - name: Install dependencies
      run: npm install
      working-directory: 461Phase2

    - name: Build Vue.js app
      run: npm run build
      working-directory: 461Phase2

    # Assuming that the output directory after building is '461Phase2/dist'
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ec2-user
      run: |
        echo "$PRIVATE_KEY" > nov20_kp.pem
        chmod 600 nov20_kp.pem
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i nov20_kp.pem" ./461Phase2/dist/ $USER@$HOST:/usr/share/nginx/html/
        rm -f nov20_kp.pem
